#!  /bin/bash 

#run_sample demo.poc.subway.AddBestSubway
#mc_analysis run 지하철역사_추천
#run_sample demo.poc.subway.BestSubway

##### 법정구역/시도
dataset import shapefile $MARMOT_DATA/행자부/법정구역_5179/시도 구역/시도 -srid EPSG:5179 -geom_col 'the_geom(EPSG:5186)' -charset euc-kr -f
mc_dataset cluster create 구역/시도


############################################################################################
##### 지오비전 데이터
############################################################################################
##### 집계구
dataset import shp $MARMOT_DATA/사업단자료/지오비전/집계구/2015 지오비전/집계구/2015 -srid EPSG:5186 -geom_col 'the_geom(EPSG:5186)' -f
mc_dataset cluster create 지오비전/집계구/2015
dataset import shp $MARMOT_DATA/사업단자료/지오비전/집계구/2018 지오비전/집계구/2018 -srid EPSG:5186 -geom_col 'the_geom(EPSG:5186)' -charset euc-kr -f
mc_dataset cluster create 지오비전/집계구/2018

##### 유동인구 (2015)
upload_files $MARMOT_DATA/사업단자료/지오비전/유동인구/2015/시간대 data/지오비전/유동인구/2015/시간대 -glob '**/*.st'
#upload_files $MARMOT_DATA/사업단자료/지오비전/유동인구/2015/시간대 data/지오비전/유동인구/2015/시간대 -glob '**/*.txt'
mc_dataset bind data/지오비전/유동인구/2015/시간대 지오비전/유동인구/2015/월별_시간대 -type text -geom_col 'the_geom(EPSG:5186)' -f
mc_dataset bind data/지오비전/유동인구/2015/시간대 지오비전/유동인구/2016/월별_시간대 -type text -geom_col 'the_geom(EPSG:5186)' -f
mc_dataset bind data/지오비전/유동인구/2015/시간대 지오비전/유동인구/2017/월별_시간대 -type text -geom_col 'the_geom(EPSG:5186)' -f

##### 지오비전 카드매출 (2015)
upload_files $MARMOT_DATA/사업단자료/지오비전/카드매출/2015/시간대 data/지오비전/카드매출/2015/시간대 -glob '**/*.st'
#upload_files $MARMOT_DATA/사업단자료/지오비전/카드매출/2015/시간대 data/지오비전/카드매출/2015/시간대 -glob '**/*.txt'
mc_dataset bind data/지오비전/카드매출/2015/시간대 지오비전/카드매출/2015/일별_시간대 -type text -f
mc_dataset bind data/지오비전/카드매출/2015/시간대 지오비전/카드매출/2016/일별_시간대 -type text -f
mc_dataset bind data/지오비전/카드매출/2015/시간대 지오비전/카드매출/2017/일별_시간대 -type text -f


##### 지하철
dataset import shapefile $MARMOT_DATA/사업단자료/전국지하철_2015/역사 교통/지하철/역사 -geom_col 'the_geom(EPSG:5186)' -charset euc-kr -f
mc_dataset cluster create 교통/지하철/역사

##### 나비콜 택시 운행 로그
upload_files $MARMOT_DATA/나비콜/201601 data/나비콜/택시로그 -glob '**/*.st' 
#upload_files $MARMOT_DATA/나비콜/201601 data/나비콜/택시로그 -glob '**/*.dat'
mc_dataset bind data/나비콜/택시로그 나비콜/택시로그 -type text -geom_col 'the_geom(EPSG:5186)' -f

###############################################################################################################################################
###############################################################################################################################################
###############################################################################################################################################

##### GIS건물통합정보(국가중점데이터)
dataset import shp $MARMOT_DATA/국가공간정보포털/GIS건물통합정보/2019.07 건물/GIS건물통합정보_2019 -charset euc-kr -geom_col 'the_geom(EPSG:5174)' -f
mc_dataset cluster create 건물/GIS건물통합정보_2019 -workers 23
mc_dataset thumbnail create 건물/GIS건물통합정보_2019 500000

##### 연속지적도_2017 (사업단)
dataset import shp $MARMOT_DATA/사업단자료/연속지적도_2017 구역/연속지적도_2017 -charset utf-8 -geom_col 'the_geom(EPSG:5186)' -f
mc_dataset cluster create 구역/연속지적도_2017 -workers 51
mc_dataset thumbnail create  구역/연속지적도_2017 1000000

##### 행정동코드
mc_dataset import shp $MARMOT_DATA/사업단자료/행정동코드 구역/행정동코드 -geom_col 'the_geom(EPSG:5186)' -charset utf-8 -f
mc_dataset cluster create 구역/행정동코드

##### 도로망
dataset import shapefile $MARMOT_DATA/기타/표준노드링크/20180531/LINK.shp 교통/도로/링크 -geom_col 'the_geom(EPSG:5186)' -charset euc-kr -f
mc_dataset cluster create 교통/도로/링크 -workers 3

##### 병원
mc_dataset improt csv $MARMOT_DATA/공공데이터포털/병원 POI/병원 -quote '"' -header_first -point_cols '경도,위도'	\
		-srid EPSG:4326 -geom_col 'the_geom(EPSG:5186)' -f
mc_dataset cluster create POI/병원

##### 노인복지시설
dataset import shp $MARMOT_DATA/사업단자료/노인복지시설_통합 POI/노인복지시설 -f -geom_col 'the_geom(EPSG:5186)' -charset utf-8
mc_dataset cluster create POI/노인복지시설

##### 주유소 가격
mc_dataset import csv $MARMOT_DATA/공공데이터포털/주유소_가격 POI/주유소_가격 -delim '|' -header_first	\
			-point_cols '경도|위도' -srid EPSG:4326 -geom_col 'the_geom(EPSG:5186)' -f
mc_dataset cluster create POI/주유소_가격

###############################################################################################################################################
###############################################################################################################################################
###############################################################################################################################################

##### 성연령별인구
dataset import shp $MARMOT_DATA/사업단자료_2018/성연령별인구/2000년 주민/성연령별인구/2000년 -geom_col 'the_geom(EPSG:5186)' -charset utf-8 -f
dataset import shp $MARMOT_DATA/사업단자료_2018/성연령별인구/2005년 주민/성연령별인구/2005년 -geom_col 'the_geom(EPSG:5186)' -charset utf-8 -f
dataset import shp $MARMOT_DATA/사업단자료_2018/성연령별인구/2010년 주민/성연령별인구/2010년 -geom_col 'the_geom(EPSG:5186)' -charset utf-8 -f
dataset import shp $MARMOT_DATA/사업단자료_2018/성연령별인구/2015년 주민/성연령별인구/2015년 -geom_col 'the_geom(EPSG:5186)' -charset utf-8 -f

mc_dataset bind pop_age_interval_2000 tmp/result -type gwave -f
mc_dataset bind etri_demo_2000y_20a_5186 gwave/etri_demo_2000y_20a_5186 -type gwave -f
mc_dataset bind etri_demo_2000y_20a_5186 gwave/etri_demo_2000y_30a_5186 -type gwave -f
mc_dataset bind etri_demo_2000y_20a_5186 gwave/etri_demo_2000y_40a_5186 -type gwave -f
mc_dataset bind etri_demo_2000y_20a_5186 gwave/etri_demo_2000y_50a_5186 -type gwave -f
mc_dataset bind etri_demo_2000y_20a_5186 gwave/etri_demo_2005y_20a_5186 -type gwave -f
mc_dataset bind etri_demo_2000y_20a_5186 gwave/etri_demo_2005y_30a_5186 -type gwave -f
mc_dataset bind etri_demo_2000y_20a_5186 gwave/etri_demo_2005y_40a_5186 -type gwave -f
mc_dataset bind etri_demo_2000y_20a_5186 gwave/etri_demo_2005y_50a_5186 -type gwave -f
mc_dataset bind etri_demo_2000y_20a_5186 gwave/etri_demo_2010y_20a_5186 -type gwave -f
mc_dataset bind etri_demo_2000y_20a_5186 gwave/etri_demo_2010y_30a_5186 -type gwave -f
mc_dataset bind etri_demo_2000y_20a_5186 gwave/etri_demo_2010y_40a_5186 -type gwave -f
mc_dataset bind etri_demo_2000y_20a_5186 gwave/etri_demo_2010y_50a_5186 -type gwave -f
mc_dataset bind etri_demo_2000y_20a_5186 gwave/etri_demo_2015y_20a_5186 -type gwave -f
mc_dataset bind etri_demo_2000y_20a_5186 gwave/etri_demo_2015y_30a_5186 -type gwave -f
mc_dataset bind etri_demo_2000y_20a_5186 gwave/etri_demo_2015y_40a_5186 -type gwave -f
mc_dataset bind etri_demo_2000y_20a_5186 gwave/etri_demo_2015y_50a_5186 -type gwave -f
